name: Run Tests

on:
  pull_request:
  push:
    branches:
      - main

env:
  # See https://github.com/jruby/jruby/issues/5509
  JAVA_OPTS: "--add-opens java.xml/com.sun.org.apache.xerces.internal.impl=org.jruby.dist"

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [3.2, 3.3, 3.4, jruby]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run tests
      run: bundle exec rake
